// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package q

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/q/open_academy_course"
)

type OpenAcademyCourseCondition = open_academy_course.Condition

// OpenAcademyCourse returns a open_academy_course.ConditionStart for OpenAcademyCourseModel
func OpenAcademyCourse() open_academy_course.ConditionStart {
	return open_academy_course.ConditionStart{
		ConditionStart: &models.ConditionStart{},
	}
}
